version: "3"

services:
  mysql:
    platform: linux/x86_64
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_DATABASE: musinsa
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: root
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/mysql:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 30s
      timeout: 10s
      retries: 5

  application:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shopping-category
    restart: on-failure
    ports:
      - "8081:8080"
    depends_on:
      - mysql

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - application
